# Jekyll Settings
excerpt_separator: <!--more-->
exclude: ["CNAME", "README.md", "LICENSE"]
paginate: 5
paginate_path: ":num"
permalink: pretty
sass:
    style: :compressed

# Gems
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Custom Variables
analytics: #100929437
author:
  email: "tanvi3@illinois.edu"
  github: "tanvi-m"
  linkedin: "tanvi-malhotra"
  name: "Tanvi Malhotra"
  uri: "https://tanvimalhotra.github.io/"
description: "Personal website of Tanvi Malhotra, MS UIUC."
title: "Tanvi Malhotra"
url: "https://tanvimalhotra.github.io/"
