# Jekyll Settings
excerpt_separator: <!--more-->
exclude: ["README.md", "LICENSE"]
paginate: 5
paginate_path: ":num"
permalink: pretty
sass:
    style: :compressed

# Gems
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Custom Variables
analytics: 
author:
  email: "&#109;&#97;&#98;&#101;&#114;&#103;&#101;&#114;&#54;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;"
  github: "tanvi-m"
  linkedin: "tanvi-malhotra"
  name: "Tanvi Malhotra"
  uri: "http://tanvimalhotra.github.io"
description: "Personal website of Tanvi Malhotra, MS Information Management."
title: "Tanvi Malhotra"
url: "http://tanvimalhotra.github.io"
